sudo: required
services:
  - docker

language: c
compiler: gcc

cache:
    directories:
      - $HOME/.cache

env:
    global:
      - PRODUCT=tarantool-migrate
    matrix:
      - TARGET=test
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=el DIST=8
      - OS=fedora DIST=28
      - OS=fedora DIST=28
      - OS=fedora DIST=29
      - OS=fedora DIST=30
      - OS=fedora DIST=31
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=bionic
      - OS=ubuntu DIST=eoan
      - OS=ubuntu DIST=focal
      - OS=debian DIST=jessie
      - OS=debian DIST=stretch
      - OS=debian DIST=buster

matrix:
    allow_failures:
#      - env: OS=el DIST=6
#      - env: OS=el DIST=7
#      - env: OS=fedora DIST=24
#      - env: OS=fedora DIST=25
#      - env: OS=ubuntu DIST=precise
#      - env: OS=ubuntu DIST=trusty
#      - env: OS=ubuntu DIST=xenial
#      - env: OS=ubuntu DIST=yakkety
#      - env: OS=debian DIST=wheezy
#      - env: OS=debian DIST=jessie
#      - env: OS=debian DIST=stretch

script:
  - git describe --long
  - |
    if [ "${TARGET}" = "test" ]; then
        ./test.sh;
    else
        git clone https://github.com/packpack/packpack.git packpack;
        packpack/packpack;
    fi;

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud from master branch
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_3"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_4"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  # Deploy packages to PackageCloud from tags
  # see:
  #   * https://github.com/tarantool/tarantool/issues/3745
  #   * https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_3"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: packagecloud
    username: tarantool
    repository: "2_4"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb}
    skip_cleanup: true
    on:
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
